[custom]
;神器专用clash规则，魔改自ACL4SSR的mini规则魔改
;去除去广告规则,实测有Bug
;超级精简神器专用，合并空星节点和实星节点，同意按照几星分级，并删减0.1倍率的花星节点

ruleset=🎯 China,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 China,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🎯 China,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎡 Proxy,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=🎡 Proxy,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🎡 Proxy,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyLite.list
ruleset=🎯 China,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 China,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/ChinaCompanyIp.list
ruleset=🎯 China,[]GEOIP,CN
ruleset=🐟 FINAL,[]FINAL

custom_proxy_group=🎡 Proxy`select`[]🚀 ★`[]🚀 ★★`[]🚀 ★★★`[]DIRECT
custom_proxy_group=🚀 ★★★`select`[]♻️ ★★★`(★★★|✰✰✰)`[]DIRECT
custom_proxy_group=🚀 ★★`select`[]♻️ ★★`^(?!.*(★★★|✰✰✰)).*(★★|✰✰).*$`[]DIRECT
custom_proxy_group=🚀 ★`select`[]♻️ ★`^(?!.*(★★★|✰✰✰|★★|✰✰)).*(★|✰).*$`[]DIRECT
custom_proxy_group=♻️ ★★★`url-test`(★★★|✰✰✰)`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=♻️ ★★`url-test`^(?!.*(★★★|✰✰✰)).*(★★|✰✰).*$`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=♻️ ★`url-test`^(?!.*(★★★|✰✰✰|★★|✰✰)).*(★|✰).*$`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🎯 China`select`[]DIRECT`[]🎡 Proxy
custom_proxy_group=🐟 FINAL`select`[]🎡 Proxy`[]🚀 ★`[]🚀 ★★`[]🚀 ★★★`[]DIRECT

enable_rule_generator=true
overwrite_original_rules=true