[custom]
;神器专用clash规则，魔改自ACL4SSR的mini规则魔改
;去除去广告规则,实测有Bug
;超级精简神器专用，合并空星节点和实星节点，同意按照几星分级，并删减0.1倍率的花星节点

ruleset=🎯 China,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 China,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🎯 China,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎡 Proxy,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=🎡 Proxy,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🎡 Proxy,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyLite.list
ruleset=🎯 China,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 China,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/ChinaCompanyIp.list
ruleset=🎯 China,[]GEOIP,CN
ruleset=🐟 FINAL,[]FINAL

custom_proxy_group=🎡 Proxy`select`[]🚀 ★`[]🇭🇰 Hong Kong`[]🇹🇼 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇺🇸 America`[]🇰🇷 Korea`[]🚀 ★★`[]🚀 ★★★`[]DIRECT

custom_proxy_group=🇭🇰 Hong Kong`select`[]♻️ 香港自动`(🇭🇰|香港|HK|Hong)`[]DIRECT
custom_proxy_group=🇹🇼 Taiwan`select`[]♻️ 台湾自动`(🇹🇼|台湾|台|TW|Tai)`[]DIRECT
custom_proxy_group=🇸🇬 Singapore`select`[]♻️ 狮城自动`(🇸🇬|新加坡|坡|狮城|SG|Sing)`[]DIRECT
custom_proxy_group=🇯🇵 Japan`select`[]♻️ 日本自动`(🇯🇵|日本|日|东京|大阪|JP|Japan)`[]DIRECT
custom_proxy_group=🇺🇸 America`select`[]♻️ 美国自动`(🇺🇸|美国|美|洛杉矶|US|America)`[]DIRECT
custom_proxy_group=🇰🇷 Korea`select`[]♻️ 韩国自动`(🇰🇷|盘古斧|八丈矛|狂神铠|韩国|KR)`[]DIRECT

custom_proxy_group=🚀 ★★★`select`[]♻️ ★★★`(★★★|✰✰✰)`[]DIRECT
custom_proxy_group=🚀 ★★`select`[]♻️ ★★`^(?!.*(★★★|✰✰✰)).*(★★|✰✰).*$`[]DIRECT
custom_proxy_group=🚀 ★`select`[]♻️ ★`^(?!.*(★★★|✰✰✰|★★|✰✰)).*(★|✰).*$`[]DIRECT

custom_proxy_group=♻️ 香港自动`url-test`(🇭🇰|香港|HK|Hong)`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=♻️ 台湾自动`url-test`(🇹🇼|台湾|台|TW|Tai)`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=♻️ 狮城自动`url-test`(🇸🇬|新加坡|坡|狮城|SG|Sing)`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=♻️ 日本自动`url-test`(🇯🇵|日本|日|东京|大阪|JP|Japan)`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=♻️ 美国自动`url-test`(🇺🇸|美国|美|洛杉矶|US|America)`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=♻️ 韩国自动`url-test`(🇰🇷|盘古斧|八丈矛|狂神铠|韩国|KR)`http://cp.cloudflare.com/generate_204`300,,50

custom_proxy_group=♻️ ★★★`url-test`(★★★|✰✰✰)`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=♻️ ★★`url-test`^(?!.*(★★★|✰✰✰)).*(★★|✰✰).*$`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=♻️ ★`url-test`^(?!.*(★★★|✰✰✰|★★|✰✰)).*(★|✰).*$`http://cp.cloudflare.com/generate_204`300,,50

custom_proxy_group=🎯 China`select`[]DIRECT`[]🎡 Proxy
custom_proxy_group=🐟 FINAL`select`[]🎡 Proxy`[]🚀 ★`[]🇭🇰 Hong Kong`[]🇹🇼 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇺🇸 America`[]🇰🇷 Korea`[]🚀 ★★`[]🚀 ★★★`[]DIRECT

enable_rule_generator=true
overwrite_original_rules=true